tasks:
  - before: "bash ./assets/scripts/updateurl.sh"
  - command: "docker-compose up -d && docker exec wordpress sh -c 'exec chown -R www-data /var/www/html/wp-content'; alias dbsave='bash ./assets/scripts/dbsave.sh'"
